[consumers]
[consumers.event-consumer]
exchange = "event-consumer"
queue = "event-consumer"
routing_key = ""
type = "direct"
auto_delete = false
durable = true
exclusive = false
#disable=true
qos = 50
worker_count = 1
#additional_bindings =["ex1:routing_key_1", "ex2:routing_key_2", "ex3"]

[logger]
level="debug"
