version: '3.8'

services:

  consul:
    image: consul:1.15.4
    container_name: consul
    ports:
      - "8500:8500"               # Consul HTTP API
      - "8600:8600/udp"           # DNS Interface
    command: "agent -dev -client=0.0.0.0"
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - "5672:5672"               # RabbitMQ main port
      - "15672:15672"             # RabbitMQ management console
    networks:
      - app-network

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"               # Redis port
    networks:
      - app-network

  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app_db
    ports:
      - "5432:5432"               # PostgreSQL port
    networks:
      - app-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
